version: '3'
services:
    ms-sql-server:
        image: hesoyam1298/inf:inc
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Pa55word2019"
        ports: 
            - "1433:1433"
    web-api:
        build: .
        environment:
            DBServer: "ms-sql-server"
        ports:
            - "8080:80"
    angular-api:
        image: dockerangular
        build: dockerangular/.
        ports: 
            - "8000:80"
    
        